FROM python:3.12-slim

SHELL ["/bin/bash", "-c"]

ENV PYTHONUNBUFFERED=1

EXPOSE 22
EXPOSE 80

VOLUME ["/app"]

WORKDIR /app

# Install necessary packages
RUN apt-get update && apt-get install -y \
    make \
    zip \
    nginx \
    openssh-server

# Install Python dependencies
COPY requirements.txt .
COPY requirements-dev.txt .
RUN python3 -m pip install --upgrade pip \
    && pip install -r requirements.txt \
    && pip install -r requirements-dev.txt

# Configure SSH
RUN mkdir /var/run/sshd \
    && echo 'root:password' | chpasswd \
    && sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

ENTRYPOINT ["/bin/bash", "-c", "service nginx start && /usr/sbin/sshd -D"]
