name: Integration

on:
  push:
    branches:
      - '**'
    paths:
      - '**.py'
      - '.github/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check coding style
        uses: sansanlatulipe/github-actions/python-lint@main
        with:
          python-version: 3.x
          exclude-path: resources/test

  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run unit tests
        uses: sansanlatulipe/github-actions/python-unittest@main
        with:
          python-version: ${{ matrix.python-version }}
          coverage-path: ./resources/lib/
          coverage-threshold: 50
