name: Integration

on:
  push:
    branches:
      - '**'
    paths:
      - '**.py'
      - '.github/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check coding style
        uses: sansanlatulipe/github-actions/python-lint@main
        with:
          python-version: 3.x

  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run unit tests
        uses: sansanlatulipe/github-actions/python-unittest@main
        with:
          python-version: 3.x
          coverage-path: ./resources/lib/
          coverage-threshold: 70
